development:
 adapter: mysql2
 encoding: utf8
 reconnect: false  
 database: books_data
 #database: concept_owl_data_entry
 #database: concept_owl_live_testing
 pool: 5
 username: root
 password: root
 #socket: /tmp/mysql.sock

