# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b823d2f3f069a155a0c42bfe1903cc375a3d313eb90500fc55fd2701abc03f73f122d12fa117e4797cdf11b0241944c53e031569c611d096e2208f7aff79396

test:
  secret_key_base: 43f76f1590b37de223ccb40b07739210a78c9ddb438228b2ab7b0f31312f0a8fba173a6e85f2cf411051785349988c47f561e205b209463f3e22359d1bda4256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
